url:
  base:    '193.48.231.30'
  connect: '/connect.php'
  compte:  '/user/compteae.php'
  month:   '/user/compteae.php?page=AE&month='

form:
  domain: 'utbm'
  btn:    'Se connecter'

cookies:
  auth_cookie: 'AE2_SESS_ID'